project:
  type: website
    
website:

  title: "Pascal Lehner"
  site-url: https://pascal-lehner.github.io
  search: true
  navbar:
    left:
      - text: "Home"
        href: index.qmd
    right:
      - text: "About"
        href: about.qmd
      - text: "Publications"
        href: publications.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

lang: en
